//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeTimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BridgeTimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string Caption_Cancel {
            get {
                return ResourceManager.GetString("Caption_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsluiten.
        /// </summary>
        public static string Caption_Close {
            get {
                return ResourceManager.GetString("Caption_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Caption_OK {
            get {
                return ResourceManager.GetString("Caption_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauzeren.
        /// </summary>
        public static string Caption_Pause {
            get {
                return ResourceManager.GetString("Caption_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standaard.
        /// </summary>
        public static string Caption_RestoreDefaults {
            get {
                return ResourceManager.GetString("Caption_RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellen.
        /// </summary>
        public static string Caption_Settings {
            get {
                return ResourceManager.GetString("Caption_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten.
        /// </summary>
        public static string Caption_Start {
            get {
                return ResourceManager.GetString("Caption_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppen.
        /// </summary>
        public static string Caption_Stop {
            get {
                return ResourceManager.GetString("Caption_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleuren.
        /// </summary>
        public static string Header_Colors {
            get {
                return ResourceManager.GetString("Header_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijden.
        /// </summary>
        public static string Header_Timings {
            get {
                return ResourceManager.GetString("Header_Timings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisseltijd:.
        /// </summary>
        public static string Label_ChangeTime {
            get {
                return ResourceManager.GetString("Label_ChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisseltijd achtergrond:.
        /// </summary>
        public static string Label_ChangeTimeBackgroud {
            get {
                return ResourceManager.GetString("Label_ChangeTimeBackgroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisseltijd cijfers:.
        /// </summary>
        public static string Label_ChangeTimeForeground {
            get {
                return ResourceManager.GetString("Label_ChangeTimeForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal ronden:.
        /// </summary>
        public static string Label_NumberOfRounds {
            get {
                return ResourceManager.GetString("Label_NumberOfRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeltijd uren:.
        /// </summary>
        public static string Label_PlayingTimeHours {
            get {
                return ResourceManager.GetString("Label_PlayingTimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeltijd minuten:.
        /// </summary>
        public static string Label_PlayingTimeMinutes {
            get {
                return ResourceManager.GetString("Label_PlayingTimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeltijd achtergrond:.
        /// </summary>
        public static string Label_PlayTimeBackground {
            get {
                return ResourceManager.GetString("Label_PlayTimeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeltijd cijfers:.
        /// </summary>
        public static string Label_PlayTimeForeground {
            get {
                return ResourceManager.GetString("Label_PlayTimeForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ronde.
        /// </summary>
        public static string Label_Round {
            get {
                return ResourceManager.GetString("Label_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waarschuwen voor einde ronde:.
        /// </summary>
        public static string Label_WarningMoment {
            get {
                return ResourceManager.GetString("Label_WarningMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aflooptijd achtergrond:.
        /// </summary>
        public static string Label_WarningTimeBackground {
            get {
                return ResourceManager.GetString("Label_WarningTimeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aflooptijd cijfers:.
        /// </summary>
        public static string Label_WarningTimeForeground {
            get {
                return ResourceManager.GetString("Label_WarningTimeForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit was de laatste ronde.
        /// </summary>
        public static string Message_EventEnded {
            get {
                return ResourceManager.GetString("Message_EventEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U kunt wisselen voor ronde {0}.
        /// </summary>
        public static string Message_TakeSeatsForRound {
            get {
                return ResourceManager.GetString("Message_TakeSeatsForRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U kunt wisselen voor de volgende ronde.
        /// </summary>
        public static string Message_TakeYourSeats {
            get {
                return ResourceManager.GetString("Message_TakeYourSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridgeklok.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
